### ISSUE TITLE
Zero Stop Price From Open Stop Market Order on Deployment

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.ByBit#14]
#### Expected Behavior
LEAN fetches open orders from Bybit and creates the LEAN orders accordingly.

#### Actual Behavior
`StopMarketOrder`s have zero stop prices. `LimitOrder`s have non-zero limit prices as expected.

#### Reproducing the Problem
Place `StopMarketOrder` orders with Binance Futures, and stop the algorithm. Redeploy and verify the new stop price is zero.

#### System Information
Observed with  LEAN CLI.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by zurpet** [comment]
![bybit-account-orders](https://github.com/QuantConnect/Lean.Brokerages.ByBit/assets/46728641/b7af3f82-d799-41d6-8922-7ccaed3a7fea)
![bybit-lean-redeployment](https://github.com/QuantConnect/Lean.Brokerages.ByBit/assets/46728641/ac6590c8-afc5-4814-8e37-dd3b43d6fd30)

Hi Alex, I am attaching a few screenshots so that you can check more details on this. All of the original orders were created by Lean (by the strategy/algorithm), then we've stopped the algorithm (running on Ubuntu VPS, using Lean CLI, by pressing CTRL+C), and re-deployed it. We were testing using Object Store as a persistence layer in between re-deployments, so we've encountered this issue by accident.

**Comment by zurpet** [comment]
Hi team, we've noticed another possible issue - when Lean fetches the order quantity, it doesn't really respect whether the order quantity is negative or positive (SELL or BUY). We'd expect that all of those orders on the screenshot would have negative quantity when fetched by the `self.Transactions.GetOrdersByBrokerageId()` method (because they are all SELL orders), but the orders were fetched with a positive quantity, which is an issue since it doesn't match with the original order qty and we can't really rely on the information Lean gives us in this regard.

**Comment by Martin-Molinero** [comment]
Thank you @zurpet for the report, we will solve this asap 👍

**Comment by zurpet** [comment]
Hi guys, is there any realistic ETA on this issue?
